[profile.default]
solc = '0.8.21'
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]
eth_rpc_url = "http://localhost:8545"

[profile.scroll-sepolia]
eth_rpc_url = "https://sepolia-rpc.scroll.io/"

[profile.op-goerli]
eth_rpc_url = "https://opt-goerli.g.alchemy.com/v2/UF7j76yPWLAbLszYLS50UzHQYg3K3m9X"

[profile.polygon-mumbai]
eth_rpc_url = "https://polygon-mumbai.g.alchemy.com/v2/V1ADvYFrja2nCZH19GPBcQootx5bHZYz"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config